# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created: Mon Apr 23 10:55:22 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 848)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.alpha1Label = QtGui.QLabel(self.centralwidget)
        self.alpha1Label.setGeometry(QtCore.QRect(770, 400, 21, 17))
        self.alpha1Label.setObjectName("alpha1Label")
        self.alphaSlide = QtGui.QSlider(self.centralwidget)
        self.alphaSlide.setEnabled(False)
        self.alphaSlide.setGeometry(QtCore.QRect(100, 380, 691, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaSlide.sizePolicy().hasHeightForWidth())
        self.alphaSlide.setSizePolicy(sizePolicy)
        self.alphaSlide.setSizeIncrement(QtCore.QSize(0, 0))
        self.alphaSlide.setMaximum(20)
        self.alphaSlide.setSingleStep(1)
        self.alphaSlide.setPageStep(1)
        self.alphaSlide.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlide.setTickPosition(QtGui.QSlider.TicksBelow)
        self.alphaSlide.setTickInterval(1)
        self.alphaSlide.setObjectName("alphaSlide")
        self.blendPB = QtGui.QPushButton(self.centralwidget)
        self.blendPB.setEnabled(False)
        self.blendPB.setGeometry(QtCore.QRect(360, 760, 158, 27))
        self.blendPB.setObjectName("blendPB")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 701, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadStartPB = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.loadStartPB.setObjectName("loadStartPB")
        self.horizontalLayout.addWidget(self.loadStartPB)
        spacerItem = QtGui.QSpacerItem(206, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loadEndPB = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.loadEndPB.setObjectName("loadEndPB")
        self.horizontalLayout.addWidget(self.loadEndPB)
        self.blendedLabel = QtGui.QLabel(self.centralwidget)
        self.blendedLabel.setGeometry(QtCore.QRect(390, 730, 101, 17))
        self.blendedLabel.setObjectName("blendedLabel")
        self.alphaLabel = QtGui.QLabel(self.centralwidget)
        self.alphaLabel.setGeometry(QtCore.QRect(30, 380, 41, 17))
        self.alphaLabel.setObjectName("alphaLabel")
        self.alpha0Label = QtGui.QLabel(self.centralwidget)
        self.alpha0Label.setGeometry(QtCore.QRect(90, 400, 21, 17))
        self.alpha0Label.setObjectName("alpha0Label")
        self.alphaValue = QtGui.QTextEdit(self.centralwidget)
        self.alphaValue.setEnabled(False)
        self.alphaValue.setGeometry(QtCore.QRect(830, 380, 51, 31))
        self.alphaValue.setReadOnly(True)
        self.alphaValue.setObjectName("alphaValue")
        self.trianglesBox = QtGui.QCheckBox(self.centralwidget)
        self.trianglesBox.setEnabled(False)
        self.trianglesBox.setGeometry(QtCore.QRect(380, 360, 121, 22))
        self.trianglesBox.setObjectName("trianglesBox")
        self.image2Label = QtGui.QLabel(self.centralwidget)
        self.image2Label.setGeometry(QtCore.QRect(630, 350, 101, 17))
        self.image2Label.setObjectName("image2Label")
        self.image1Label = QtGui.QLabel(self.centralwidget)
        self.image1Label.setGeometry(QtCore.QRect(150, 350, 101, 17))
        self.image1Label.setObjectName("image1Label")
        self.image2View = QtGui.QGraphicsView(self.centralwidget)
        self.image2View.setGeometry(QtCore.QRect(480, 40, 400, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image2View.sizePolicy().hasHeightForWidth())
        self.image2View.setSizePolicy(sizePolicy)
        self.image2View.setMouseTracking(True)
        self.image2View.setObjectName("image2View")
        self.image1View = QtGui.QGraphicsView(self.centralwidget)
        self.image1View.setGeometry(QtCore.QRect(20, 40, 400, 300))
        self.image1View.setMouseTracking(True)
        self.image1View.setObjectName("image1View")
        self.blendedView = QtGui.QGraphicsView(self.centralwidget)
        self.blendedView.setGeometry(QtCore.QRect(250, 420, 400, 300))
        self.blendedView.setMouseTracking(True)
        self.blendedView.setObjectName("blendedView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha1Label.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.blendPB.setText(QtGui.QApplication.translate("MainWindow", "Blend", None, QtGui.QApplication.UnicodeUTF8))
        self.loadStartPB.setText(QtGui.QApplication.translate("MainWindow", "Load Starting Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadEndPB.setText(QtGui.QApplication.translate("MainWindow", "Load Ending Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.blendedLabel.setText(QtGui.QApplication.translate("MainWindow", "Blending Result", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaLabel.setText(QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha0Label.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.trianglesBox.setText(QtGui.QApplication.translate("MainWindow", "Show Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.image2Label.setText(QtGui.QApplication.translate("MainWindow", "Ending Image", None, QtGui.QApplication.UnicodeUTF8))
        self.image1Label.setText(QtGui.QApplication.translate("MainWindow", "Starting Image", None, QtGui.QApplication.UnicodeUTF8))

